-- Copyright 2015 Mirantis, Inc.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
local gse_policy = require 'gse_policy'

local M = {}
setfenv(1, M) -- Remove external access to contain everything in the module

local policies = {
    ['availability_of_members']={
        gse_policy.new({
            status='down',
            trigger={
                logical_operator='or',
                rules={
                    {
                        ['function']='count',
                        ['arguments']={'okay'},
                        ['relational_operator']='==',
                        ['threshold']=0,
                    },
                }
            },
        }),
        gse_policy.new({
            status='critical',
            trigger={
                logical_operator='and',
                rules={
                    {
                        ['function']='count',
                        ['arguments']={'okay'},
                        ['relational_operator']='==',
                        ['threshold']=1,
                    },
                    {
                        ['function']='count',
                        ['arguments']={'critical','down'},
                        ['relational_operator']='>',
                        ['threshold']=1,
                    },
                }
            },
        }),
        gse_policy.new({
            status='warning',
            trigger={
                logical_operator='or',
                rules={
                    {
                        ['function']='percent',
                        ['arguments']={'okay'},
                        ['relational_operator']='<',
                        ['threshold']=100,
                    },
                }
            },
        }),
        gse_policy.new({
            status='okay',
            trigger={
                logical_operator='or',
                rules={
                    {
                        ['function']='percent',
                        ['arguments']={'okay'},
                        ['relational_operator']='==',
                        ['threshold']=100,
                    },
                }
            },
        }),
        gse_policy.new({
            status='unknown',
        }),
    },
    ['highest_severity']={
        gse_policy.new({
            status='down',
            trigger={
                logical_operator='or',
                rules={
                    {
                        ['function']='count',
                        ['arguments']={'down'},
                        ['relational_operator']='>',
                        ['threshold']=0,
                    },
                }
            },
        }),
        gse_policy.new({
            status='critical',
            trigger={
                logical_operator='or',
                rules={
                    {
                        ['function']='count',
                        ['arguments']={'critical'},
                        ['relational_operator']='>',
                        ['threshold']=0,
                    },
                }
            },
        }),
        gse_policy.new({
            status='warning',
            trigger={
                logical_operator='or',
                rules={
                    {
                        ['function']='count',
                        ['arguments']={'warning'},
                        ['relational_operator']='>',
                        ['threshold']=0,
                    },
                }
            },
        }),
        gse_policy.new({
            status='okay',
            trigger={
                logical_operator='or',
                rules={
                    {
                        ['function']='count',
                        ['arguments']={'okay'},
                        ['relational_operator']='>',
                        ['threshold']=0,
                    },
                }
            },
        }),
        gse_policy.new({
            status='unknown',
        }),
    },
    ['majority_of_members']={
        gse_policy.new({
            status='down',
            trigger={
                logical_operator='or',
                rules={
                    {
                        ['function']='percent',
                        ['arguments']={'down'},
                        ['relational_operator']='>',
                        ['threshold']=50,
                    },
                }
            },
        }),
        gse_policy.new({
            status='critical',
            trigger={
                logical_operator='and',
                rules={
                    {
                        ['function']='percent',
                        ['arguments']={'critical','down'},
                        ['relational_operator']='>',
                        ['threshold']=20,
                    },
                    {
                        ['function']='percent',
                        ['arguments']={'okay'},
                        ['relational_operator']='<',
                        ['threshold']=50,
                    },
                }
            },
        }),
        gse_policy.new({
            status='warning',
            trigger={
                logical_operator='or',
                rules={
                    {
                        ['function']='percent',
                        ['arguments']={'okay'},
                        ['relational_operator']='<',
                        ['threshold']=50,
                    },
                }
            },
        }),
        gse_policy.new({
            status='okay',
        }),
    },
    ['majority_of_node_members']={
        gse_policy.new({
            status='down',
            trigger={
                logical_operator='or',
                rules={
                    {
                        ['function']='percent',
                        ['arguments']={'down'},
                        ['relational_operator']='==',
                        ['threshold']=100,
                    },
                }
            },
        }),
        gse_policy.new({
            status='critical',
            trigger={
                logical_operator='and',
                rules={
                    {
                        ['function']='percent',
                        ['arguments']={'critical','down'},
                        ['relational_operator']='>=',
                        ['threshold']=50,
                    },
                }
            },
        }),
        gse_policy.new({
            status='warning',
            trigger={
                logical_operator='or',
                rules={
                    {
                        ['function']='percent',
                        ['arguments']={'critical','down','unknown','warning'},
                        ['relational_operator']='>',
                        ['threshold']=0,
                    },
                }
            },
        }),
        gse_policy.new({
            status='okay',
        }),
    },
    ['status_of_members']={
        gse_policy.new({
            status='down',
            trigger={
                logical_operator='or',
                rules={
                    {
                        ['function']='percent',
                        ['arguments']={'down'},
                        ['relational_operator']='==',
                        ['threshold']=100,
                    },
                }
            },
        }),
        gse_policy.new({
            status='critical',
            trigger={
                logical_operator='and',
                rules={
                    {
                        ['function']='count',
                        ['arguments']={'okay','warning'},
                        ['relational_operator']='<=',
                        ['threshold']=1,
                    },
                    {
                        ['function']='count',
                        ['arguments']={'critical','down','unknown'},
                        ['relational_operator']='>',
                        ['threshold']=0,
                    },
                }
            },
        }),
        gse_policy.new({
            status='warning',
            trigger={
                logical_operator='or',
                rules={
                    {
                        ['function']='percent',
                        ['arguments']={'okay'},
                        ['relational_operator']='!=',
                        ['threshold']=100,
                    },
                }
            },
        }),
        gse_policy.new({
            status='okay',
            trigger={
                logical_operator='or',
                rules={
                    {
                        ['function']='percent',
                        ['arguments']={'okay'},
                        ['relational_operator']='==',
                        ['threshold']=100,
                    },
                }
            },
        }),
        gse_policy.new({
            status='unknown',
        }),
    },
}

function find(policy)
    return policies[policy]
end

return M

