-- Copyright 2015 Mirantis, Inc.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
local M = {}
setfenv(1, M) -- Remove external access to contain everything in the module

clusters = {
    ['apache']={
        ['members']={'check','worker'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='availability_of_members'
    },
    ['ceilometer-api']={
        ['members']={'backends'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['ceilometer-api-check']={
        ['members']={'vip'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['ceph-mon-cluster']={
        ['members']={'capacity','health'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['ceph-mon-service']={
        ['members']={'check'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='availability_of_members'
    },
    ['ceph-osd-service']={
        ['members']={'check'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='availability_of_members'
    },
    ['cinder-api']={
        ['members']={'backends','http_errors'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['cinder-api-check']={
        ['members']={'vip'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['cinder-api-endpoint']={
        ['members']={'endpoint'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='availability_of_members'
    },
    ['cinder-logs']={
        ['members']={'error'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='highest_severity'
    },
    ['cinder-scheduler']={
        ['members']={'workers'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['cinder-v2-api-check']={
        ['members']={'vip'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['cinder-volume']={
        ['members']={'workers'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['elasticsearch-cluster']={
        ['members']={'health'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['elasticsearch-service']={
        ['members']={'check'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='availability_of_members'
    },
    ['glance-api']={
        ['members']={'backends','http_errors'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['glance-api-check']={
        ['members']={'vip'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['glance-api-endpoint']={
        ['members']={'endpoint'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='availability_of_members'
    },
    ['glance-logs']={
        ['members']={'error'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='highest_severity'
    },
    ['glance-registry-api']={
        ['members']={'backends'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['haproxy-openstack']={
        ['members']={'check'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='availability_of_members'
    },
    ['heat-api']={
        ['members']={'backends','http_errors'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['heat-api-check']={
        ['members']={'vip'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['heat-api-endpoint']={
        ['members']={'endpoint'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='availability_of_members'
    },
    ['heat-cfn-api']={
        ['members']={'backends'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['heat-cfn-api-check']={
        ['members']={'vip'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['heat-cfn-api-endpoint']={
        ['members']={'endpoint'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='availability_of_members'
    },
    ['heat-cloudwatch-api']={
        ['members']={'backends'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['heat-logs']={
        ['members']={'error'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='highest_severity'
    },
    ['horizon-web']={
        ['members']={'backends','http_errors'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['influxdb-api-check']={
        ['members']={'vip'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['influxdb-service']={
        ['members']={'check'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='availability_of_members'
    },
    ['keystone-admin-api']={
        ['members']={'backends','http_errors'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['keystone-logs']={
        ['members']={'error'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='highest_severity'
    },
    ['keystone-public-api']={
        ['members']={'backends','http_errors'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['keystone-public-api-check']={
        ['members']={'vip'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['keystone-public-api-endpoint']={
        ['members']={'endpoint'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='availability_of_members'
    },
    ['keystone-response-time']={
        ['members']={'duration'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['libvirt-service']={
        ['members']={'check'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='majority_of_node_members'
    },
    ['memcached-service']={
        ['members']={'check'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='availability_of_members'
    },
    ['mysql']={
        ['members']={'check','node-status'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='majority_of_members'
    },
    ['mysqld-tcp']={
        ['members']={'backends'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['neutron-api']={
        ['members']={'backends','http_errors'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['neutron-api-check']={
        ['members']={'vip'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['neutron-api-endpoint']={
        ['members']={'endpoint'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='availability_of_members'
    },
    ['neutron-dhcp']={
        ['members']={'workers'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['neutron-l3']={
        ['members']={'workers'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['neutron-logs']={
        ['members']={'error'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='highest_severity'
    },
    ['neutron-logs-compute']={
        ['members']={'error'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='highest_severity'
    },
    ['neutron-metadata']={
        ['members']={'workers'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['neutron-openvswitch']={
        ['members']={'workers'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['nova-api']={
        ['members']={'backends','http_errors'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['nova-api-check']={
        ['members']={'vip'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['nova-api-endpoint']={
        ['members']={'endpoint'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='availability_of_members'
    },
    ['nova-cert']={
        ['members']={'workers'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['nova-compute']={
        ['members']={'workers'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['nova-conductor']={
        ['members']={'workers'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['nova-consoleauth']={
        ['members']={'workers'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['nova-free-memory']={
        ['members']={'nova-aggregates-free-memory','nova-free-memory'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['nova-free-vcpu']={
        ['members']={'nova-free-vcpu'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['nova-instances']={
        ['members']={'creation-time'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='majority_of_members'
    },
    ['nova-logs']={
        ['members']={'error'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='highest_severity'
    },
    ['nova-logs-compute']={
        ['members']={'error'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='highest_severity'
    },
    ['nova-metadata-api']={
        ['members']={'backends'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['nova-novncproxy-websocket']={
        ['members']={'backends'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['nova-scheduler']={
        ['members']={'workers'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['pacemaker-service']={
        ['members']={'check'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='availability_of_members'
    },
    ['rabbitmq-cluster']={
        ['members']={'disk','memory','pacemaker','queue'},
        ['hints']={},
        ['group_by']='member',
        ['policy']='highest_severity'
    },
    ['rabbitmq-service']={
        ['members']={'check'},
        ['hints']={},
        ['group_by']='hostname',
        ['policy']='majority_of_members'
    },
}

return M
